services:
  nginx:
    image: nginx:stable
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/src:/var/www/html
    depends_on:
      - php
    mem_limit: 150m
    cpus: 0.75

  php:
    build: ./php
    volumes:
      - ./php/src:/var/www/html
    mem_limit: 15g
    cpus: 3.0
